num_joint: 31
node_mask: [0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 17, 18, 20, 21, 24, 25, 27, 28] 
max_frame: 64 # 데이터 전체 Frame 

raw_data_name: CMU
raw_data_type: asfamc
raw_data_dir: ./data/CMU/asfamc/

save_dir: ./processed_data/CMU/asfamc/
pre_processor: preprocessor.asfamc.Processor

debug: True
# print_log: True